import type { Product } from '@/types'

export const demoProducts: Product[] = [
  {
    id: 'demo-1',
    name: '핸드메이드 가죽 지갑',
    price: 29000,
    description: '장인이 직접 손으로 만든 천연 가죽 지갑입니다. 부드러운 질감과 내구성이 뛰어나며, 사용할수록 더 멋스러운 빈티지 감성을 느낄 수 있어요.',
    image_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400',
    stock: 15,
    category: '잡화',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    name: '유기농 제주 녹차 세트',
    price: 18000,
    description: '제주도 청정 지역에서 자란 유기농 녹차를 엄선해 담았습니다. 은은한 풀향과 깔끔한 뒷맛이 일상에 여유를 선물해줄 거예요.',
    image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    stock: 30,
    category: '식품',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    name: '무선 블루투스 이어폰',
    price: 45000,
    description: '선 없이 자유롭게! 30시간 배터리와 액티브 노이즈 캔슬링으로 음악에 완전히 빠져드세요. 방수 기능 내장으로 운동할 때도 걱정 없어요.',
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400',
    stock: 8,
    category: '전자기기',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    name: '천연 아로마 비누 세트 (3입)',
    price: 15000,
    description: '라벤더, 로즈마리, 페퍼민트 세 가지 향으로 구성된 천연 비누 세트입니다. 화학 성분 없이 피부에 순하게 사용할 수 있어요.',
    image_url: 'https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=400',
    stock: 25,
    category: '뷰티',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    name: '레트로 캔버스 백팩',
    price: 52000,
    description: '복고풍 디자인과 실용적인 수납공간을 동시에! 15인치 노트북이 들어가는 크기로 학교, 직장, 여행 어디서나 스타일리시하게 매고 다닐 수 있어요.',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    stock: 12,
    category: '가방',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    name: '수제 도자기 머그컵',
    price: 22000,
    description: '도예가가 한 땀 한 땀 직접 만든 수제 머그컵입니다. 손에 쥐었을 때 편안한 그립감과 따뜻한 온기가 아침을 더 특별하게 만들어줄 거예요.',
    image_url: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400',
    stock: 20,
    category: '주방',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-7',
    name: '국산 꿀 (아카시아꿀 500g)',
    price: 32000,
    description: '국내 양봉장에서 채취한 100% 순수 아카시아꿀입니다. 첨가물 없이 자연 그대로의 달콤함을 담았어요. 선물용 패키지로도 인기 만점!',
    image_url: 'https://images.unsplash.com/photo-1471943038054-9f2ece5e00c9?w=400',
    stock: 18,
    category: '식품',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-8',
    name: '린넨 쿠션 커버 (2개 세트)',
    price: 26000,
    description: '자연스러운 린넨 소재로 어느 공간에도 잘 어울리는 쿠션 커버입니다. 세탁이 간편하고 통기성이 좋아 사계절 내내 쾌적하게 사용할 수 있어요.',
    image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
    stock: 0,
    category: '홈데코',
    created_at: new Date().toISOString(),
  },
]
